# Generated by Django 3.2 on 2021-05-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entyre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('sex', models.CharField(max_length=15)),
                ('dob', models.DateField(max_length=8)),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('insurance_comp', models.TextField()),
                ('insurance_num', models.IntegerField()),
            ],
        ),
    ]
