# Generated by Django 3.2 on 2021-05-09 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diag_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('sex', models.CharField(max_length=15)),
                ('dob', models.DateField(max_length=8)),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('insurance_comp', models.CharField(max_length=100)),
                ('insurance_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=15)),
                ('strength', models.CharField(max_length=15)),
                ('dosage', models.CharField(max_length=20)),
                ('form', models.CharField(max_length=15)),
                ('ofDiagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.diagnosis')),
            ],
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='ofPatient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
    ]
